### ISSUE TITLE
Is addition ever distributive over multiplication?

### ISSUE THREAD

**Issue by CalabashSquash** [warlock-labs/noether#6]
Regarding the following lines:
https://github.com/warlock-labs/noether/blob/08bface4c5979d5e1896feaa13b63a23e6e2ba97/src/lib.rs#L29-L30

I have a reasonably naive mathematical question: Are there ever any algebraic structures wherein addition (or whatever is represented by +) is distributive over multiplication (or whatever * is)?

**Comment by 0xAlcibiades** [comment]
It's a good question, I'm not sure that's ever the case. Would refer you to do some digging on it though.

**Comment by merolish** [comment]
[Related discussion.](https://math.stackexchange.com/questions/23304/when-addition-distributes-over-multiplication)

**Comment by 0xAlcibiades** [comment]
So with lattices, eh?
