### ISSUE TITLE
Support implementing FiniteField for a big integer order

### ISSUE THREAD

**Issue by tyilo** [warlock-labs/noether#7]
Currently `FiniteField` is defined as:

```rust
pub trait FiniteField: Field {
    /// Returns the characteristic of the field.
    fn characteristic() -> u64;

    /// Returns the number of elements in the field.
    fn order() -> u64;
}
```

If you want to work in a finite field where the characteristic/order can't fit in a `u64`, you can't implement `FiniteField`.

**Comment by 0xAlcibiades** [comment]
Feel free to make a change where it's a scalar type which is abstract!

**Comment by geet-eth** [comment]
Does this look okay? @tyilo 
`pub trait FiniteField: Field {
    /// Returns the characteristic of the field.
    fn characteristic() -> BigUint;

    fn order() -> BigUint

    fn extension_degree() -> u32 [
        let char = Self::characteristic();
        let order = Self::order();
        (order.bits()-1) / (char.bits() -1) as u32
    ]
}`

**Comment by geet-eth** [comment]
does this look okay @tyilo 
```
pub trait FiniteField: Field {
    /// Returns the characteristic of the field.
    fn characteristic() -> BigUint;

    fn order() -> BigUint

    fn extension_degree() -> u32 [
        let char = Self::characteristic();
        let order = Self::order();
        (order.bits()-1) / (char.bits() -1) as u32
    ]
}
```

**Comment by geet-eth** [comment]
using rug[](https://crates.io/crates/rug) also makes more sense(bigint kinda slow) here but unsure if thats the direction team wants to take
